### ISSUE TITLE
"executing stop command"

### ISSUE THREAD

**Issue by darksider90** [b0mbays/ha-cast#3]
hi, i config 2 HA with your integration, but for the second i have a Problem.

In the log i see this : 
"Current device map: {'couloir': {'dashboard_url': 'http://192.168.1.250:8123/dashboard-cast/0/default_view?kiosk', 'dashboard_state_name': 'Dummy', 'media_state_name': 'PLAYING', 'volume': -1, 'start_time': datetime.time(5, 0), 'end_time': datetime.time(1, 0), 'instance_change': False}}
2024-05-21 13:52:24.519 INFO (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] Current local time: 13:52:24.517929
2024-05-21 13:52:24.519 INFO (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] Local time is inside the allowed casting time for couloir. Start time: 05:00:00 - End time: 01:00:00
2024-05-21 13:52:41.695 INFO (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] HA Dashboard (or media) is NOT playing on couloir!
2024-05-21 13:52:41.696 INFO (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] Casting dashboard to couloir
2024-05-21 13:52:41.702 DEBUG (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] Executing stop command...
2024-05-21 13:52:58.801 WARNING (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] Failed to extract volume information from status_output for couloir. Using default volume 5.
2024-05-21 13:52:58.806 DEBUG (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] Setting volume to 0...
2024-05-21 13:53:07.397 INFO (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] Executing the dashboard cast command...
2024-05-21 13:53:15.941 INFO (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] Setting volume to 5...
2024-05-21 13:54:04.490 DEBUG (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] All device map: {'couloir': {'instances': [{'dashboard_url': 'http://192.168.1.250:8123/dashboard-cast/0/default_view?kiosk', 'dashboard_state_name': 'Dummy', 'media_state_name': 'PLAYING', 'volume': -1, 'start_time': datetime.time(5, 0), 'end_time': datetime.time(1, 0), 'instance_change': False}], 'current_instance': 0}}"

the problem is : "executing stop command"

But why ? 

external acces with https : ok
HA fix : ok

i'm lost..

could you help me ?

Thank's

**Comment by b0mbays** [comment]
"Executing stop command" is a part of the casting process to stop anything that might be on the display before casting the HA dashboard.

What is your problem? Is the casting not working at all? 🤔

**Comment by b0mbays** [comment]
I've just realized this is the raspberry pi version. It's severely outdated unfortunately. Are you able to use the more up to date Home Assistant addon instead?

https://github.com/b0mbays/continuously_casting_dashboards

**Comment by darksider90** [comment]
oh yes sorry. It's the new version on my instance. I'm just posted here . it's a mistake.

But yes, no interaction on my google nest hub. :(

**Comment by b0mbays** [comment]
No problem! Can you post your full configuration for CCD inside your configuration.yaml file?

**Comment by darksider90** [comment]
yes 👍 
`continuously_casting_dashboards:
  logging_level: debug #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 40
  start_time: "05:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device>
  end_time: "01:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually o>
  devices:
    "couloir": 
      - dashboard_url: "http://192.168.1.250:8123/dashboard-cast/0/default_view?kiosk" #Required: Dashboard URL to be casted (This must be the local I>
        volume: 5 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
`

**Comment by b0mbays** [comment]
Can you post it again but keep the formatting?

Explained here:
 https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by darksider90** [comment]
Yes, ;)

```
continuously_casting_dashboards:
  logging_level: debug #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 40
  start_time: "05:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device>
  end_time: "01:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually o>
  devices:
    "couloir": 
      - dashboard_url: "http://192.168.1.250:8123/dashboard-cast/0/default_view?kiosk" #Required: Dashboard URL to be casted (This must be the local I>
        volume: 5 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
```
